name: Reusable global workflow

on:
  workflow_call:
    inputs:
      test-path:
        required: true
        type: string
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.triage.outputs.output1 }}
        
jobs:
  triage:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: ${{ inputs.test-path }}        
    - name: Run script
      run: |
        echo "Input to reusable workflow: ${{ inputs.test-path }}"
    - id: step1
      run: echo "firstword=hello" >> $GITHUB_OUTPUT
